[package]
name = "wgpu_first_steps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.14.0"
winit = "0.27.4"
raw-window-handle = "0.5.0"
pollster = "0.2.5"